# Generated by Django 3.2 on 2021-05-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marca'},
        ),
    ]
