# Generated by Django 3.2 on 2021-06-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
