# Generated by Django 3.2 on 2021-06-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_alter_comprasdet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdet',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='fechaModificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='fechaModificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fechaModificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
